#!/bin/bash
# Docker Compose Compatibility Wrapper
# Ensures docker-compose command is available regardless of installation method

set -e # Exit on any error

# Get script directory and source dependencies
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "${SCRIPT_DIR}")")"
source "${PROJECT_ROOT}/scripts/lib/common.sh"

# ═══════════════════════════════════════════════════════════════════════════════
# 🐳 DOCKER COMPOSE COMPATIBILITY FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

# Check current Docker Compose availability
check_docker_compose_availability() {
    log_info "Checking Docker Compose availability..."
    
    local compose_available=false
    local compose_type=""
    
    # Check for docker compose plugin (modern approach)
    if docker compose version &> /dev/null; then
        compose_available=true
        compose_type="plugin"
        log_success "Docker Compose plugin detected"
    # Check for standalone docker-compose command
    elif command -v docker-compose &> /dev/null && docker-compose version &> /dev/null; then
        compose_available=true
        compose_type="standalone"
        log_success "Docker Compose standalone detected"
    # Check for docker-compose plugin via docker CLI
    elif docker --help 2>/dev/null | grep -q "compose"; then
        compose_available=true
        compose_type="cli_plugin"
        log_success "Docker Compose plugin available via docker CLI"
    fi
    
    if [[ "$compose_available" == "true" ]]; then
        log_info "Docker Compose type: $compose_type"
        return 0
    else
        log_error "No Docker Compose installation detected"
        return 1
    fi
}

# Create compatibility wrapper script
create_compatibility_wrapper() {
    log_info "Creating Docker Compose compatibility wrapper"
    
    # Check if wrapper already exists
    if [[ -f "/usr/local/bin/docker-compose" ]]; then
        log_info "Docker Compose wrapper already exists at /usr/local/bin/docker-compose"
        
        # Check if it's our wrapper
        if grep -q "JarvisJR Stack" "/usr/local/bin/docker-compose" 2>/dev/null; then
            log_info "Existing wrapper is from JarvisJR Stack - updating"
        else
            log_warning "Existing docker-compose found - backing up before replacing"
            execute_cmd "sudo mv /usr/local/bin/docker-compose /usr/local/bin/docker-compose.backup.$(date +%s)" "Backup existing docker-compose"
        fi
    fi
    
    # Create the wrapper script
    cat > /tmp/docker-compose << 'EOF'
#!/bin/bash
# Docker Compose Compatibility Wrapper
# Automatically generated by JarvisJR Stack
# Provides docker-compose command compatibility for all Docker installations

# Function to detect and use the best available Docker Compose method
detect_and_execute() {
    # Method 1: Try docker compose plugin (Docker Desktop, modern installations)
    if docker compose version &>/dev/null 2>&1; then
        exec docker compose "$@"
    
    # Method 2: Try standalone docker-compose binary
    elif command -v docker-compose.real &>/dev/null && docker-compose.real version &>/dev/null 2>&1; then
        exec docker-compose.real "$@"
    
    # Method 3: Try system docker-compose in alternative paths
    elif [[ -x "/usr/bin/docker-compose" ]] && /usr/bin/docker-compose version &>/dev/null 2>&1; then
        exec /usr/bin/docker-compose "$@"
    elif [[ -x "/usr/local/bin/docker-compose.real" ]] && /usr/local/bin/docker-compose.real version &>/dev/null 2>&1; then
        exec /usr/local/bin/docker-compose.real "$@"
    
    # Method 4: Check if docker CLI has compose as subcommand
    elif docker --help 2>/dev/null | grep -q "compose"; then
        exec docker compose "$@"
    
    # No Docker Compose found
    else
        echo "Error: No working Docker Compose installation found" >&2
        echo "Please install one of the following:" >&2
        echo "  - Docker Desktop (includes compose plugin)" >&2
        echo "  - docker-compose-plugin: apt install docker-compose-plugin" >&2
        echo "  - standalone docker-compose: apt install docker-compose" >&2
        exit 1
    fi
}

# Execute the detection and delegation
detect_and_execute "$@"
EOF
    
    # Install the wrapper
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY-RUN] Would install Docker Compose wrapper to /usr/local/bin/docker-compose"
        return 0
    fi
    
    execute_cmd "sudo mv /tmp/docker-compose /usr/local/bin/docker-compose" "Install compatibility wrapper"
    execute_cmd "sudo chmod +x /usr/local/bin/docker-compose" "Make wrapper executable"
    execute_cmd "sudo chown root:root /usr/local/bin/docker-compose" "Set wrapper ownership"
    
    log_success "Docker Compose compatibility wrapper installed successfully"
}

# Test the wrapper functionality
test_wrapper_functionality() {
    log_info "Testing Docker Compose wrapper functionality"
    
    # Test version command
    if /usr/local/bin/docker-compose version &>/dev/null; then
        local version_output=$(/usr/local/bin/docker-compose version 2>&1)
        log_success "Wrapper version check passed"
        log_info "Version output: $(echo "$version_output" | head -1)"
    else
        log_error "Wrapper version check failed"
        return 1
    fi
    
    # Test help command
    if /usr/local/bin/docker-compose --help &>/dev/null; then
        log_success "Wrapper help command passed"
    else
        log_error "Wrapper help command failed"
        return 1
    fi
    
    log_success "Docker Compose wrapper functionality verified"
}

# Install standalone Docker Compose if no version is available
install_standalone_docker_compose() {
    log_info "Installing standalone Docker Compose as fallback"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY-RUN] Would install standalone Docker Compose"
        return 0
    fi
    
    local compose_version="v2.24.1"
    local compose_url="https://github.com/docker/compose/releases/download/${compose_version}/docker-compose-$(uname -s)-$(uname -m)"
    
    log_info "Downloading Docker Compose $compose_version"
    execute_cmd "sudo curl -L \"$compose_url\" -o /usr/local/bin/docker-compose.real" "Download Docker Compose binary"
    execute_cmd "sudo chmod +x /usr/local/bin/docker-compose.real" "Make Docker Compose executable"
    execute_cmd "sudo chown root:root /usr/local/bin/docker-compose.real" "Set Docker Compose ownership"
    
    # Verify the standalone installation
    if /usr/local/bin/docker-compose.real version &>/dev/null; then
        log_success "Standalone Docker Compose installed and verified"
    else
        log_error "Standalone Docker Compose installation failed verification"
        return 1
    fi
}

# Remove compatibility wrapper
remove_wrapper() {
    log_info "Removing Docker Compose compatibility wrapper"
    
    if [[ -f "/usr/local/bin/docker-compose" ]]; then
        # Check if it's our wrapper
        if grep -q "JarvisJR Stack" "/usr/local/bin/docker-compose" 2>/dev/null; then
            execute_cmd "sudo rm /usr/local/bin/docker-compose" "Remove JarvisJR wrapper"
            log_success "JarvisJR Docker Compose wrapper removed"
        else
            log_warning "Docker Compose at /usr/local/bin/docker-compose is not JarvisJR wrapper - leaving unchanged"
        fi
    else
        log_info "No Docker Compose wrapper found to remove"
    fi
    
    # Remove standalone installation if it exists
    if [[ -f "/usr/local/bin/docker-compose.real" ]]; then
        execute_cmd "sudo rm /usr/local/bin/docker-compose.real" "Remove standalone Docker Compose"
        log_success "Standalone Docker Compose removed"
    fi
}

# Show current Docker Compose status
show_status() {
    log_section "Docker Compose Status Report"
    
    echo "=== Current Docker Compose Installation Status ==="
    echo ""
    
    # Check docker compose plugin
    if docker compose version &>/dev/null 2>&1; then
        echo "✓ Docker Compose Plugin: Available"
        echo "  Version: $(docker compose version 2>/dev/null | head -1 || echo 'Unknown')"
    else
        echo "✗ Docker Compose Plugin: Not Available"
    fi
    
    # Check standalone docker-compose
    if command -v docker-compose &>/dev/null && docker-compose version &>/dev/null 2>&1; then
        echo "✓ Standalone docker-compose: Available"
        echo "  Location: $(which docker-compose)"
        echo "  Version: $(docker-compose version 2>/dev/null | head -1 || echo 'Unknown')"
    else
        echo "✗ Standalone docker-compose: Not Available"
    fi
    
    # Check wrapper
    if [[ -f "/usr/local/bin/docker-compose" ]]; then
        if grep -q "JarvisJR Stack" "/usr/local/bin/docker-compose" 2>/dev/null; then
            echo "✓ JarvisJR Wrapper: Installed"
            echo "  Location: /usr/local/bin/docker-compose"
            if /usr/local/bin/docker-compose version &>/dev/null; then
                echo "  Status: Functional"
            else
                echo "  Status: Non-functional"
            fi
        else
            echo "⚠ Other wrapper/binary: Present at /usr/local/bin/docker-compose"
        fi
    else
        echo "✗ JarvisJR Wrapper: Not Installed"
    fi
    
    # Check standalone fallback
    if [[ -f "/usr/local/bin/docker-compose.real" ]]; then
        echo "✓ Standalone Fallback: Available"
        echo "  Location: /usr/local/bin/docker-compose.real"
        if /usr/local/bin/docker-compose.real version &>/dev/null; then
            echo "  Status: Functional"
        else
            echo "  Status: Non-functional"
        fi
    else
        echo "✗ Standalone Fallback: Not Available"
    fi
    
    echo ""
    echo "=== Recommendation ==="
    
    # Provide recommendations based on current state
    if docker compose version &>/dev/null 2>&1; then
        echo "✓ Docker Compose is working via plugin - no additional setup needed"
    elif command -v docker-compose &>/dev/null && docker-compose version &>/dev/null 2>&1; then
        echo "✓ Docker Compose is working via standalone binary - no additional setup needed"
    else
        echo "⚠ No working Docker Compose detected - run 'setup' to install"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# 🎯 MAIN FUNCTION
# ═══════════════════════════════════════════════════════════════════════════════

main() {
    case "${1:-setup}" in
        "setup"|"install")
            log_section "Docker Compose Compatibility Setup"
            
            if ! check_docker_compose_availability; then
                log_warning "No Docker Compose found - installing standalone version"
                install_standalone_docker_compose
            fi
            
            create_compatibility_wrapper
            test_wrapper_functionality
            log_success "Docker Compose compatibility setup completed"
            ;;
        "test"|"verify")
            log_section "Docker Compose Compatibility Test"
            if check_docker_compose_availability; then
                if [[ -f "/usr/local/bin/docker-compose" ]]; then
                    test_wrapper_functionality
                else
                    log_success "Docker Compose available but no wrapper needed"
                fi
            else
                log_error "Docker Compose compatibility test failed"
                return 1
            fi
            ;;
        "remove"|"uninstall")
            log_section "Docker Compose Wrapper Removal"
            remove_wrapper
            ;;
        "status"|"check")
            show_status
            ;;
        *)
            echo "Docker Compose Compatibility Wrapper"
            echo ""
            echo "Usage: $0 [COMMAND]"
            echo ""
            echo "Commands:"
            echo "  setup, install    Setup Docker Compose compatibility wrapper"
            echo "  test, verify      Test wrapper functionality"
            echo "  remove, uninstall Remove wrapper and fallback installation"
            echo "  status, check     Show current Docker Compose status"
            echo ""
            echo "Examples:"
            echo "  $0 setup          # Install compatibility wrapper"
            echo "  $0 status         # Check current status"
            echo "  $0 test           # Test functionality"
            echo "  $0 remove         # Remove wrapper"
            ;;
    esac
}

# Execute main if script is run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi