#!/bin/bash

# JStack Documentation Update System
# Handles automatic documentation updates when sites are added or removed

set -e

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "${PROJECT_ROOT}/scripts/lib/common.sh"
source "${PROJECT_ROOT}/scripts/settings/config.sh"

# Load configuration
load_config
export_config

# ═══════════════════════════════════════════════════════════════════════════════
# 📋 DOCUMENTATION TEMPLATES SYSTEM
# ═══════════════════════════════════════════════════════════════════════════════

# Generate README template for new sites
generate_site_readme_template() {
    local domain="$1"
    local site_path="$2"
    
    local readme_file="$site_path/README.md"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY RUN] Would generate README template for: $domain"
        return 0
    fi
    
    cat > "$readme_file" << EOF
# Site Configuration: $domain

Generated: $(date)
JStack Site Management

## Site Overview

**Primary Domain**: $domain
**Site Path**: $site_path
**Status**: Active
**Added**: $(date)

## Subdomain Configuration

This site is configured with the following subdomains:

- **Supabase API**: ${SUPABASE_SUBDOMAIN:-supabase}.$domain
- **Supabase Studio**: ${STUDIO_SUBDOMAIN:-studio}.$domain
- **N8N Workflows**: ${N8N_SUBDOMAIN:-n8n}.$domain

## Service Access

After deployment, your services will be accessible at:

- 🗄️ **Supabase API**: https://${SUPABASE_SUBDOMAIN:-supabase}.$domain
- 🎨 **Supabase Studio**: https://${STUDIO_SUBDOMAIN:-studio}.$domain
- 🔄 **N8N Workflows**: https://${N8N_SUBDOMAIN:-n8n}.$domain

## Configuration Files

### Required Files

- \`site.json\` - Site-specific configuration
- \`docker-compose.override.yml\` - Container overrides (optional)
- \`nginx.conf\` - Custom NGINX configuration (optional)

### Site Configuration Example (\`site.json\`)

\`\`\`json
{
  "domain": "$domain",
  "compliance_profile": "default",
  "ssl": {
    "enabled": true,
    "auto_renew": true
  },
  "services": {
    "supabase": {
      "enabled": true,
      "subdomain": "${SUPABASE_SUBDOMAIN:-supabase}"
    },
    "n8n": {
      "enabled": true,
      "subdomain": "${N8N_SUBDOMAIN:-n8n}"
    },
    "studio": {
      "enabled": true,
      "subdomain": "${STUDIO_SUBDOMAIN:-studio}"
    }
  },
  "security": {
    "rate_limiting": true,
    "firewall_rules": [],
    "monitoring": true
  }
}
\`\`\`

## Compliance and Security

This site is monitored for compliance with:

- **SOC 2 Type II**: System and Organization Controls
- **GDPR**: General Data Protection Regulation
- **ISO 27001**: Information Security Management

### Compliance Profile

**Profile**: \${DEFAULT_COMPLIANCE_PROFILE:-default}
**Monitoring**: Enabled
**Audit Retention**: \${COMPLIANCE_AUDIT_RETENTION:-90d}
**Reporting**: \${COMPLIANCE_REPORT_SCHEDULE:-Weekly}

## Management Commands

### Add This Site to JStack
\`\`\`bash
./jstack.sh --add-site $site_path
\`\`\`

### Remove This Site from JStack
\`\`\`bash
./jstack.sh --remove-site $site_path
\`\`\`

### Check Site Status
\`\`\`bash
./jstack.sh --compliance-check
\`\`\`

## Troubleshooting

### Common Issues

1. **SSL Certificate Issues**
   - Ensure DNS points to the correct server IP
   - Check firewall allows ports 80 and 443
   - Verify email is configured in jstack.config

2. **Service Not Accessible**
   - Check container status: \`docker ps\`
   - Check NGINX logs: \`docker logs jarvis-nginx\`
   - Verify DNS resolution: \`dig $domain\`

3. **Compliance Issues**
   - Run compliance check: \`./jstack.sh --compliance-check\`
   - Check compliance logs in \`/opt/jarvis-security/audit/\`

### Support

- **Configuration**: Check jstack.config settings
- **Logs**: Located in \`${BASE_DIR}/logs/\`
- **Documentation**: See project documentation in \`docs/\`

## Last Updated

$(date)

---

*This documentation was automatically generated by the JStack documentation system.*
EOF

    log_success "Generated README template: $readme_file"
}

# Generate site.json template
generate_site_config_template() {
    local domain="$1"
    local site_path="$2"
    local compliance_profile="${3:-default}"
    
    local config_file="$site_path/site.json"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY RUN] Would generate site.json template for: $domain"
        return 0
    fi
    
    cat > "$config_file" << EOF
{
  "domain": "$domain",
  "compliance_profile": "$compliance_profile",
  "created": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "ssl": {
    "enabled": true,
    "auto_renew": true,
    "email": "${EMAIL:-admin@$domain}"
  },
  "subdomains": {
    "supabase": "${SUPABASE_SUBDOMAIN:-supabase}",
    "studio": "${STUDIO_SUBDOMAIN:-studio}",
    "n8n": "${N8N_SUBDOMAIN:-n8n}"
  },
  "services": {
    "supabase": {
      "enabled": true,
      "memory_limit": "${POSTGRES_MEMORY_LIMIT:-4G}",
      "cpu_limit": "${POSTGRES_CPU_LIMIT:-2.0}"
    },
    "n8n": {
      "enabled": true,
      "memory_limit": "${N8N_MEMORY_LIMIT:-2G}",
      "cpu_limit": "${N8N_CPU_LIMIT:-1.0}"
    },
    "nginx": {
      "enabled": true,
      "memory_limit": "${NGINX_MEMORY_LIMIT:-256M}",
      "cpu_limit": "${NGINX_CPU_LIMIT:-0.5}"
    }
  },
  "security": {
    "rate_limiting": {
      "api": "${NGINX_RATE_LIMIT_API:-10r/s}",
      "general": "${NGINX_RATE_LIMIT_GENERAL:-30r/s}",
      "webhooks": "${NGINX_RATE_LIMIT_WEBHOOKS:-100r/s}"
    },
    "firewall_rules": [],
    "monitoring": {
      "enabled": true,
      "health_checks": true,
      "performance_monitoring": true,
      "security_monitoring": true
    },
    "apparmor": {
      "enabled": "${APPARMOR_ENABLED:-true}",
      "profile": "docker-jarvis"
    }
  },
  "backup": {
    "enabled": true,
    "schedule": "${BACKUP_SCHEDULE:-0 2 * * 0}",
    "retention": "${DATABASE_BACKUP_RETENTION:-1}"
  },
  "metadata": {
    "environment": "${DEPLOYMENT_ENVIRONMENT:-production}",
    "service_user": "${SERVICE_USER:-jarvis}",
    "base_directory": "${BASE_DIR:-${BASE_DIR}}",
    "last_updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  }
}
EOF

    log_success "Generated site configuration template: $config_file"
}

# Update project documentation index
update_documentation_index() {
    local action="$1"  # "add" or "remove"
    local domain="$2"
    local site_path="$3"
    
    local docs_index="$PROJECT_ROOT/docs/sites-index.md"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY RUN] Would update documentation index for $action: $domain"
        return 0
    fi
    
    # Create documentation index if it doesn't exist
    if [[ ! -f "$docs_index" ]]; then
        cat > "$docs_index" << EOF
# JStack - Sites Documentation Index

Generated: $(date)
Last Updated: $(date)

## Managed Sites

This document provides an index of all sites managed by this JStack instance.

EOF
    fi
    
    case "$action" in
        "add")
            # Add site to index
            cat >> "$docs_index" << EOF

### $domain

- **Domain**: $domain
- **Site Path**: $site_path
- **Added**: $(date)
- **Status**: Active
- **Configuration**: [$site_path/site.json]($site_path/site.json)
- **README**: [$site_path/README.md]($site_path/README.md)
- **Compliance Profile**: ${DEFAULT_COMPLIANCE_PROFILE:-default}

**Service URLs**:
- Supabase API: https://${SUPABASE_SUBDOMAIN:-supabase}.$domain
- Supabase Studio: https://${STUDIO_SUBDOMAIN:-studio}.$domain  
- N8N Workflows: https://${N8N_SUBDOMAIN:-n8n}.$domain

EOF
            log_success "Added $domain to documentation index"
            ;;
        "remove")
            # Remove site from index (mark as removed)
            if grep -q "### $domain" "$docs_index"; then
                # Create temporary file with site marked as removed
                local temp_index=$(mktemp)
                sed "/### $domain/,/^$/c\\
### $domain (REMOVED)\\
\\
- **Domain**: $domain\\
- **Removed**: $(date)\\
- **Status**: Removed\\
- **Archive Date**: $(date)\\
" "$docs_index" > "$temp_index"
                
                mv "$temp_index" "$docs_index"
                log_success "Marked $domain as removed in documentation index"
            else
                log_warning "Site $domain not found in documentation index"
            fi
            ;;
    esac
    
    # Update last modified timestamp
    sed -i "s/Last Updated:.*/Last Updated: $(date)/" "$docs_index"
}

# Generate deployment guide for a site
generate_deployment_guide() {
    local domain="$1"
    local site_path="$2"
    
    local guide_file="$site_path/DEPLOYMENT.md"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY RUN] Would generate deployment guide for: $domain"
        return 0
    fi
    
    cat > "$guide_file" << EOF
# Deployment Guide: $domain

Generated: $(date)

## Pre-Deployment Requirements

### DNS Configuration
Ensure the following DNS records point to your server IP:

\`\`\`
A    $domain                    -> YOUR_SERVER_IP
A    ${SUPABASE_SUBDOMAIN:-supabase}.$domain      -> YOUR_SERVER_IP  
A    ${STUDIO_SUBDOMAIN:-studio}.$domain          -> YOUR_SERVER_IP
A    ${N8N_SUBDOMAIN:-n8n}.$domain                -> YOUR_SERVER_IP
\`\`\`

### Firewall Requirements
Ensure the following ports are open:
- **Port 80**: HTTP (Let's Encrypt challenges)
- **Port 443**: HTTPS (All services)
- **Port 22**: SSH (Management access)

## Deployment Steps

### 1. Prepare Site Configuration

Copy the site template to your desired location:
\`\`\`bash
mkdir -p $site_path
cp -r /path/to/site/template/* $site_path/
\`\`\`

### 2. Configure Site Settings

Edit \`$site_path/site.json\`:
\`\`\`bash
nano $site_path/site.json
\`\`\`

Key settings to verify:
- **domain**: $domain
- **compliance_profile**: ${DEFAULT_COMPLIANCE_PROFILE:-default}
- **ssl.email**: Your email address
- **services**: Enable required services

### 3. Add Site to JStack

\`\`\`bash
cd /path/to/jstack
./jstack.sh --add-site $site_path
\`\`\`

### 4. Verify Deployment

Check site status:
\`\`\`bash
./jstack.sh --compliance-check
docker ps
\`\`\`

Test service accessibility:
\`\`\`bash
curl -I https://${SUPABASE_SUBDOMAIN:-supabase}.$domain
curl -I https://${STUDIO_SUBDOMAIN:-studio}.$domain
curl -I https://${N8N_SUBDOMAIN:-n8n}.$domain
\`\`\`

## Post-Deployment Configuration

### 1. Supabase Setup

1. Access Supabase Studio: https://${STUDIO_SUBDOMAIN:-studio}.$domain
2. Set up your database schema
3. Configure authentication settings
4. Set up RLS policies

### 2. N8N Setup

1. Access N8N: https://${N8N_SUBDOMAIN:-n8n}.$domain
2. Complete initial setup wizard
3. Configure your first workflows
4. Set up webhooks and integrations

### 3. Security Configuration

1. Review compliance documentation
2. Configure security policies
3. Set up monitoring and alerting
4. Test backup and recovery procedures

## Monitoring and Maintenance

### Health Checks

Monitor service health:
\`\`\`bash
# Container status
docker ps

# Service logs
docker logs jarvis-nginx
docker logs jarvis-supabase-db
docker logs jarvis-n8n

# Compliance status
./jstack.sh --compliance-check
\`\`\`

### Regular Maintenance

- **Weekly**: Review compliance reports
- **Monthly**: Update system packages and containers
- **Quarterly**: Review security policies and access controls
- **Annually**: Full security audit and penetration testing

## Troubleshooting

### Common Issues

#### SSL Certificate Problems
\`\`\`bash
# Check certificate status
openssl x509 -in /etc/ssl/certs/$domain/cert.pem -text -noout

# Renew certificates
./jstack.sh --configure-ssl
\`\`\`

#### Service Connectivity Issues
\`\`\`bash
# Test DNS resolution
dig $domain
dig ${SUPABASE_SUBDOMAIN:-supabase}.$domain

# Check NGINX configuration
docker exec jarvis-nginx nginx -t

# Restart services
./jstack.sh --restart-services
\`\`\`

#### Database Connection Issues
\`\`\`bash
# Check database status
docker exec jarvis-supabase-db pg_isready

# Check database logs
docker logs jarvis-supabase-db --tail 50
\`\`\`

### Support Resources

- **Configuration Documentation**: See \`jstack.config.default\`
- **Service Logs**: \`${BASE_DIR}/logs/\`
- **Compliance Reports**: \`/opt/jarvis-security/compliance-reports/\`
- **Backup Location**: \`${BASE_DIR}/backups/\`

## Rollback Procedure

If deployment fails or issues arise:

1. **Remove the site**:
   \`\`\`bash
   ./jstack.sh --remove-site $site_path
   \`\`\`

2. **Restore from backup** (if needed):
   \`\`\`bash
   ./jstack.sh --restore
   \`\`\```

3. **Verify system state**:
   \`\`\`bash
   ./jstack.sh --compliance-check
   \`\`\```

## Contact Information

- **System Administrator**: ${EMAIL:-admin@$domain}
- **Compliance Officer**: ${COMPLIANCE_ALERT_EMAIL:-compliance@$domain}
- **Technical Support**: support@$domain

---

*This deployment guide was automatically generated on $(date)*
EOF

    log_success "Generated deployment guide: $guide_file"
}

# ═══════════════════════════════════════════════════════════════════════════════
# 📋 MAIN DOCUMENTATION UPDATE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

# Update all documentation for a site action
update_site_documentation() {
    local action="$1"  # "add" or "remove"
    local domain="$2"
    local site_path="${3:-/sites/$domain}"
    
    log_section "Updating Documentation for $action: $domain"
    
    case "$action" in
        "add")
            # Create site directory if it doesn't exist
            if [[ ! -d "$site_path" ]]; then
                log_info "Creating site directory: $site_path"
                mkdir -p "$site_path"
            fi
            
            # Generate all documentation templates
            generate_site_readme_template "$domain" "$site_path"
            generate_site_config_template "$domain" "$site_path" "${DEFAULT_COMPLIANCE_PROFILE:-default}"
            generate_deployment_guide "$domain" "$site_path"
            
            # Update project documentation index
            update_documentation_index "add" "$domain" "$site_path"
            
            log_success "Documentation generated for new site: $domain"
            ;;
        "remove")
            # Update project documentation index
            update_documentation_index "remove" "$domain" "$site_path"
            
            log_success "Documentation updated for removed site: $domain"
            ;;
        *)
            log_error "Unknown documentation action: $action"
            return 1
            ;;
    esac
}

# Show help information
show_help() {
    cat << EOF
JStack Documentation Update System

USAGE:
    bash update_site_docs.sh [COMMAND] [OPTIONS]

COMMANDS:
    add-site DOMAIN [PATH]      Generate documentation for new site
    remove-site DOMAIN [PATH]   Update documentation for removed site
    update-index                Rebuild documentation index
    help                        Show this help message

EXAMPLES:
    # Generate documentation for new site
    bash update_site_docs.sh add-site example.com /sites/example.com

    # Update documentation for removed site
    bash update_site_docs.sh remove-site example.com

    # Rebuild documentation index
    bash update_site_docs.sh update-index

GENERATED FILES:
    - README.md              Site overview and configuration guide
    - site.json             Site configuration template
    - DEPLOYMENT.md         Complete deployment guide
    - docs/sites-index.md   Project-wide sites index

EOF
}

# Main execution
main() {
    local command="${1:-help}"
    
    case "$command" in
        "add-site")
            if [[ -z "$2" ]]; then
                log_error "Domain is required for add-site command"
                show_help
                exit 1
            fi
            update_site_documentation "add" "$2" "$3"
            ;;
        "remove-site")
            if [[ -z "$2" ]]; then
                log_error "Domain is required for remove-site command"
                show_help
                exit 1
            fi
            update_site_documentation "remove" "$2" "$3"
            ;;
        "update-index")
            log_info "Rebuilding documentation index..."
            # This would scan all sites and rebuild the index
            log_info "Index rebuild functionality would be implemented here"
            ;;
        "help"|"-h"|"--help")
            show_help
            ;;
        *)
            log_error "Unknown command: $command"
            show_help
            exit 1
            ;;
    esac
}

# Execute main function if script is run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi